version: '3.2'

services:
    client:
        image: bkouhen/docker-mean-client:latest
        restart: always
        depends_on: 
            - api
    api:
        image: bkouhen/docker-mean-api:latest
        restart: always
    nginx:
        image: bkouhen/docker-mean-nginx:latest
        restart: always
        depends_on: 
            - api
            - client
        ports: 
            - "80:80"
            - "443:443"