version: '3'

services:
    client:
        image: docker-mean-client:latest
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        depends_on: 
            - api
    api:
        image: docker-mean-api:latest
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes: 
            - /app/node_modules
            - ./backend:/app
            - ./static:/app/static
        depends_on: 
            - database
    nginx:
        image: docker-mean-nginx:latest
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        volumes: 
            - ./static:/app/static
        ports: 
            - "80:80"
        restart: always
    database:
        image: mongo
        restart: always
        volumes: 
            - database-volume:/data/db

volumes:
    database-volume: