version: '3.5'

services:
    client:
        environment: 
            - NGINX_CLIENT_PORT=4200
    api:
        volumes: 
            - static-volume:/app/static
        environment: 
            - port=3000
            - NODE_ENV=production
            - top_background=/images/email/top_background.jpg
            - carreh_logo=/images/email/carreh_logo.png
            - fb_logo=/images/email/fb_logo.png
            - ig_logo=/images/email/ig_logo.png
            - CONTACT_EMAIL=b.kouhen@gmail.com
        secrets:
            - mongo_atlas_password
            - jwt_key
            - sg_api_key
            - sg_sender
    nginx:
        volumes: 
            - static-volume:/app/static            
            - certs-volume:/etc/letsencrypt
            - certs-volume2:/etc/nginx/certs
        environment: 
            - NGINX_PORT=80
            - NGINX_TLS_PORT=443
            - NGINX_CLIENT_PORT=4200
            - NGINX_API_PORT=3000
            - NGINX_WWW_SERVER_NAME=www.carreh.tk
            - NGINX_SERVER_NAME=carreh.tk
volumes:
    static-volume:
    certs-volume:
    certs-volume2:

secrets:
    mongo_atlas_password:
        file: mongo_atlas_password.txt
        name: mongo_atlas_password_v${MONGO_PWD_VERSION}
    jwt_key:
        file: jwt_key.txt
        name: jwt_key_v${JWT_KEY_VERSION}
    sg_api_key:
        file: sg_api_key.txt
        name: sg_api_key_v${SG_API_VERSION}
    sg_sender:
        file: sg_sender.txt
        name: sg_sender_v${SG_SENDER_VERSION}