version: '3.5'

services:
    client:
        image: bkouhen/docker-mean-client:latest
        restart: always
        depends_on: 
            - api
        logging: 
            driver: syslog
            options: 
                syslog-address: "tcp://0.0.0.0:514"
                tag: docker-{{.Name}}
    api:
        image: bkouhen/docker-mean-api:latest
        restart: always
        logging: 
            driver: syslog
            options: 
                syslog-address: "tcp://0.0.0.0:514"
                tag: docker-{{.Name}}
    nginx:
        image: bkouhen/docker-mean-nginx:latest
        restart: always
        depends_on: 
            - api
            - client
        ports: 
            - "80:80"
            - "443:443"
        logging: 
            driver: syslog
            options: 
                syslog-address: "tcp://0.0.0.0:514"
                tag: docker-{{.Name}}
    syslog:
        image: bkouhen/docker-mean-syslog:latest
        restart: always
        ports:
            - 514:514
            - 514:514/udp
        cap_add: 
            - SYSLOG
    portainer:
        image: portainer/portainer
        hostname: portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-volume:/data

volumes:
    portainer-volume: