FROM nginx:1.19.0

RUN apt-get update && apt-get install -y apache2-utils

COPY ./nginx.dev.conf.template /etc/nginx/nginx.conf.template

COPY dev-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD ["nginx", "-g", "daemon off;"]